const v2 = this.RangeError;
try { v2.captureStackTrace(25676); } catch (e) {}
