const v1 = this.SuppressedError;
try { v1.captureStackTrace(); } catch (e) {}
