for (let v0 = 0; v0 < 5; v0++) {
    const v2 = WebAssembly.Exception;
    try { new v2(v0); } catch (e) {}
}
